### ISSUE TITLE
Examples don't compile

### ISSUE THREAD

**Issue by barretpj** [AcademySoftwareFoundation/openfx#117]
The shipped examples fail to build because the `linuxSymbols` file is not present.

Will fix this as part of the DrawSuite comments PR

**Comment by garyo** [comment]
Hi Phil; thanks for noticing this. I assume you're using the Makefiles to build (rather than the brand-new cmake). I notice that the cmake build is also not using the symbol file, which means the plugins it builds are exporting too many symbols. I'll be happy to bring back `linuxSymbols` and integrate it into the cmake build as well as cleaning up the plain-Make build.

I think we should just have one copy of that symbols file, rather than separate copies for the examples etc.

**Comment by barretpj** [comment]
> I assume you're using the Makefiles to build

Correct.
