### ISSUE TITLE
Example needed for handling dynamic libraries

### ISSUE THREAD

**Issue by revisionfx** [AcademySoftwareFoundation/openfx#165]
### Problem

PR:  External DLL dependency Example

It would be useful for hosts and plugin developers to have a good example to handle external to the .ofx plugin per se dependencies.
Anyone has related topics so it's all in one :)

Given:
- In OpenFX we do support network paths, which allows to set a plugin path on a network so plugins are installed only in one place.
- Also some hosts as well provide support for their own additional environment variable for specific to their app folders
- We also modified the behavior of OfxGetPlugin (also so one can right away decide if a particular plugin can or not load, here would be which one if one needs to support two variants maybe?)

So:
- Historically we have the property kOfxPluginPropFilePath
It's useful but in practice the comment for this should include:  We recommend to use OS calls (GetModleName(), dlinfo()) to more reliably figure where the plugin is loaded from.
Furthermore not all apps provide that path info at Load Plugin time... When we went that path initially we needed to wait to Describe.

- On Windows it appears to work with just using SetDLLDirectory (there is also an Add variant - it does not look so far it has been needed, unclear yet as we don't use everyone's plugin if two different vendors do that if there are consequences to that). On Mac (X-Code) and Linux if you don't know ahead where the dynamic library will be it's HARD.  It has been suggested one needs to use: "On macOS, @loader_path is the solution. On Linux, you can use RUNPATH with location set relative to $ORIGIN." As well these external library might have an effect on code-sign and notarization....  Might be bad programmer here but on Windows needed some .lib wrappers to get this to work as expected, that might be not true but once it worked never looked back.

A good example could be one that has two dll dependencies, one at GetPlugin level (load A or B depending on host, host version or if some other framework, library is installed or not) and one a delay load one, which would load the first time one invokes a symbol from it.

The delay load could be anything - it could be guarded by islicensed() or not something needed for background renders or be an huge thing not needed for a whole session... although the release part perhaps gets us in dlopen() , dlclose() space which we are trying to avoid here.

**Comment by garyo** [comment]
Not sure what you're aiming for here. Normally you link with a dll/.so, and provide that in the proper place in your installed location, setting the proper RPATH or similar so it gets found, just like any other shared lib being loaded by an executable. The dependent lib gets loaded by the dynamic loader when the plugin gets loaded. This isn't specific to OpenFX, but is just general OS-specific shared-lib handling. I don't think it makes sense to create an example plugin that does this; it's going to be OS-specific, the instructions will vary depending on your build system (xcode/MSVS/cmake/etc.) and it can get complicated.
I will note, though, that since OpenFX plugins always use a bundle structure, you can put dependent DLLs in the Resource/ folder.
But then you say "delay load" which means dlopen() or similar -- then your dependent lib can be anywhere, but you have to open it, map symbols, etc. That seems *well* beyond the scope of what we should provide in this repo.

**Comment by revisionfx** [comment]
You are saying there is a way on Mac to just put the dylib inside the plugin folder and that will work in the case where the network path is somewhere we don't know at compile or install time...  I am familiar with dlopen, trying to avoid using it. I only know the path during runtime. You say it should work to use @loader_path or @rpath relative path to the .ofx?  (e.g. @loaderpath/../Resouces is supposed to work?) -   -Wl,-rpath,'$ORIGIN'  ? Is there a definitive doc about that? :)

On Windows we can get the ofx load path and set the DLL directory at run time and it will just work without LoadLibrary (equiv to dlopen) - also delayed load is reference to VS Linker - Input - : useful as it allows us to use different libraries only when actually used. I understand that this is almost an OS feature request.
